[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/api/*"
  to = "https://cab230.hackhouse.sh/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}